security:
  user:
    name: '{cipher}AQBSgvP0hz+b3OrMCYIO7Rf58MK9jL5NzAR6tcYz+9qrIIM16dlrOojxHm9Z+jgiscJQKBnz+q1sf2ljjcz4Ixj20R6i6zZrDPPYuspaX72t1xGxFE7d616rfTMWA61Ce4VF5IpIWZWiec4K8TiI6myeO2ifS8Bq38+iOzx1VGYhlove4T3MpjMl/LU746dE53KD/2I1vtnOtSmMh5ovMP5tdUWFrDH9AfcY0QkPeMKGB9cJi4dWKxnubFaojg3EFfZmqd0DhB85VoZRzgYo8hw8WgBNgGwB4XxIeASP6DmEYQfpwA+L4DCH9Suv2aWXlhRGP3oiApm+XNg0PrmwuPhPY81ORnEPREb5juujKgJeLqhJhERQGM/GrgRy9hWzZmw='
    password: '{cipher}AQByAZarU7lXVHZmKThoO4IYeC2utiahYXGxZL1u5CQo812f/mpItz2v5vaOOOe8u1LIexh1h0vFCi4cLuzTHJtSqiv+YfEcON8wyiUiUG+sIl9mFrur1okx+hzIhpheP0R40HPc6882zhjNQPV/jm0QHROjHxY5RTlMqj6NcOvWCkfqrXbCblts4jANytjIiURIJ4/Tt1si1vFkEQsvErhyIe79tuYwFLt9XmJ1mAMQR+yd18haUb7FX2r6cea9Iz/gJLzVIHTRha1noH03xNsFyXz6nkqKL0pZ7AywpssDfxvT4rfb5HRty5FQnsCyltowTiNaDQ8ACywbSI284MaAGtquuk0QrzYa4/f/d4WdjNKOdfKYI9ejDp3aj8y8z4o='
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ZhuZhanming/{application}
eureka:
  client:
    service-url:
      defaultZone: http://${security.user.name}:${security.user.password}@localhost:8761/eureka/