spring:
  datasource:
    druid:
      url: jdbc:mysql://${mysql.host}:3306/zzming?test=true&amp;characterEncoding=UTF-8
      username: ${mysql.username}
      password: ${mysql.password}
      driver-class-name: com.mysql.jdbc.Driver
      validationQuery: select 'x'
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      max-active: 20
      filters: start
      max-wait: 2000
      initial-size: 1
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: top.zzming.model

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

default.role-id: 1002