spring:
  thymeleaf:
    cache: false
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 159357yx.
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 5
      min-idle: 1
    timeout: 0
user.file.dir: D:\\projects\\files